.TH "/home/vikbond/Documents/pi-hiwi/pi/pairinteraction/calc/wignerSymbols Directory Reference" 3 "Thu Feb 16 2017" "pairinteraction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vikbond/Documents/pi-hiwi/pi/pairinteraction/calc/wignerSymbols Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.in -1c
