.TH "/home/vikbond/Documents/pi-hiwi/pi/pairinteraction/calc/wignerSymbols/include/wignerSymbols Directory Reference" 3 "Thu Feb 16 2017" "pairinteraction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vikbond/Documents/pi-hiwi/pi/pairinteraction/calc/wignerSymbols/include/wignerSymbols Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcommonFunctions\&.h\fP"
.br
.RI "\fIDefines some common functions to the C++ and Fortran code\&. \fP"
.ti -1c
.RI "file \fBwignerSymbols\-cpp\&.h\fP"
.br
.RI "\fIDefines utility functions for the evaluation of Wigner-3j and -6j symbols\&. \fP"
.ti -1c
.RI "file \fBwignerSymbols\-fortran\&.h\fP"
.br
.RI "\fIDefines utility functions for the evaluation of Wigner-3j and -6j symbols\&. \fP"
.in -1c
