.TH "/home/vikbond/Documents/pi-hiwi/pi/pairinteraction/calc/wignerSymbols/include/wignerSymbols/commonFunctions.h" 3 "Thu Feb 16 2017" "pairinteraction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vikbond/Documents/pi-hiwi/pi/pairinteraction/calc/wignerSymbols/include/wignerSymbols/commonFunctions.h \- Defines some common functions to the C++ and Fortran code\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > double \fBWignerSymbols::sgn\fP (T val)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines some common functions to the C++ and Fortran code\&. 


.PP
\fBAuthor:\fP
.RS 4
Joey Dumont joey.dumont@gmail.com
.RE
.PP
\fBSince:\fP
.RS 4
2014-07-10
.RE
.PP
We define some functions that will be of use in both the C++ and Fortran parts of this library\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for pairinteraction from the source code\&.
