.TH "Configuration::value" 3 "Thu Feb 16 2017" "pairinteraction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Configuration::value \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvalue\fP (std::stringstream const &val)"
.br
.ti -1c
.RI "\fBvalue\fP (const \fBConfiguration::value\fP &obj)"
.br
.ti -1c
.RI "std::string \fBstr\fP () const "
.br
.ti -1c
.RI "void \fBstr\fP (std::string s)"
.br
.ti -1c
.RI "template<typename T > \fBConfiguration::value\fP & \fBoperator<<\fP (const T &rhs)"
.br
.ti -1c
.RI "template<typename T > \fBConfiguration::value\fP & \fBoperator>>\fP (T &rhs)"
.br
.ti -1c
.RI "template<typename T > const \fBConfiguration::value\fP & \fBoperator>>\fP (T &rhs) const "
.br
.ti -1c
.RI "template<typename T > \fBConfiguration::value\fP & \fBoperator=\fP (const T &rhs)"
.br
.ti -1c
.RI "\fBConfiguration::value\fP & \fBoperator=\fP (const \fBConfiguration::value\fP &rhs)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for pairinteraction from the source code\&.
