.TH "Fixture" 3 "Thu Feb 16 2017" "pairinteraction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fixture \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBQuantumDefect\fP \fBqd\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for pairinteraction from the source code\&.
