.TH "/home/vikbond/Documents/pi-hiwi/pi/pairinteraction/calc/wignerSymbols/tests/gh-issue-1.cpp" 3 "Thu Feb 16 2017" "pairinteraction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vikbond/Documents/pi-hiwi/pi/pairinteraction/calc/wignerSymbols/tests/gh-issue-1.cpp \- Tests Issue 1 of WignerSymbols (see valandil\&.github\&.com/wignerSymbols\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <wignerSymbols\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests Issue 1 of WignerSymbols (see valandil\&.github\&.com/wignerSymbols\&. 

Tests Issue 2 of WignerSymbols (see valandil\&.github\&.com/wignerSymbols\&.
.PP
\fBAuthor:\fP
.RS 4
Joey Dumont joey.dumont@gmail.com 
.RE
.PP
\fBSince:\fP
.RS 4
2014-07-11 
.RE
.PP
\fBCopyright:\fP
.RS 4
LGPL This file tests the bug described in Issue #1 of WignerSymbols (GitHub)\&. It seems that for some values of l1, the algorithm returns a set of zeros even though it should return proper coefficients\&. Permuting the l's lead to the proper output\&.
.RE
.PP
\fBAuthor:\fP
.RS 4
Joey Dumont joey.dumont@gmail.com 
.RE
.PP
\fBSince:\fP
.RS 4
2014-07-11 
.RE
.PP
\fBCopyright:\fP
.RS 4
LGPL This file tests the bug described in Issue #2 of WignerSymbols (GitHub)\&. It seems that for some values of l1, the algorithm returns a set of zeros even though it should return proper coefficients\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for pairinteraction from the source code\&.
