.TH "HamiltonianTwo" 3 "Thu Feb 16 2017" "pairinteraction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HamiltonianTwo \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHamiltonian< BasisnamesTwo >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHamiltonianTwo\fP (const \fBConfiguration\fP &config, boost::filesystem::path &path_cache, std::shared_ptr< \fBHamiltonianOne\fP > hamiltonian_one)"
.br
.ti -1c
.RI "\fBHamiltonianTwo\fP (const \fBConfiguration\fP &config, boost::filesystem::path &path_cache, std::shared_ptr< \fBHamiltonianOne\fP > hamiltonian_one1, std::shared_ptr< \fBHamiltonianOne\fP > hamiltonian_one2)"
.br
.ti -1c
.RI "void \fBcalculate\fP (const \fBConfiguration\fP &conf_tot)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for pairinteraction from the source code\&.
