.TH "Hamiltonian< T >" 3 "Thu Feb 16 2017" "pairinteraction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hamiltonian< T > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBHamiltonianmatrix\fP > \fBget\fP (size_t idx)"
.br
.ti -1c
.RI "std::shared_ptr< const \fBHamiltonianmatrix\fP > \fBget\fP (size_t idx) const "
.br
.ti -1c
.RI "std::shared_ptr< const \fBConfiguration\fP > \fBgetParams\fP (size_t idx) const "
.br
.ti -1c
.RI "size_t \fBsize\fP () const "
.br
.ti -1c
.RI "std::shared_ptr< const T > \fBnames\fP () const "
.br
.ti -1c
.RI "void \fBremoveUnnecessaryStates\fP (std::vector< bool > &necessary)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::vector< std::shared_ptr< \fBHamiltonianmatrix\fP > > \fBmatrix_diag\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBmatrix_path\fP"
.br
.ti -1c
.RI "std::vector< std::shared_ptr< \fBConfiguration\fP > > \fBparams\fP"
.br
.ti -1c
.RI "std::shared_ptr< T > \fBbasis\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for pairinteraction from the source code\&.
