.TH "HamiltonianOne" 3 "Thu Feb 16 2017" "pairinteraction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HamiltonianOne \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHamiltonian< BasisnamesOne >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHamiltonianOne\fP (const \fBConfiguration\fP &config, boost::filesystem::path &path_cache, std::shared_ptr< \fBBasisnamesOne\fP > basis_one)"
.br
.ti -1c
.RI "const \fBConfiguration\fP & \fBgetConf\fP () const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBchangeToSpherical\fP (real_t val_x, real_t val_y, real_t val_z, real_t &val_p, real_t &val_m, real_t &val_0)"
.br
.ti -1c
.RI "void \fBchangeToSpherical\fP (real_t val_x, real_t val_y, real_t val_z, std::complex< real_t > &val_p, std::complex< real_t > &val_m, std::complex< real_t > &val_0)"
.br
.ti -1c
.RI "void \fBconfigure\fP (const \fBConfiguration\fP &config)"
.br
.ti -1c
.RI "void \fBbuild\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for pairinteraction from the source code\&.
