.TH "MatrixElements" 3 "Thu Feb 16 2017" "pairinteraction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MatrixElements \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatrixElements\fP (std::string const &species, std::string const &dbname)"
.br
.ti -1c
.RI "\fBMatrixElements\fP (const \fBConfiguration\fP &config, std::string const &species, std::string const &dbname)"
.br
.ti -1c
.RI "void \fBprecalculateElectricMomentum\fP (std::shared_ptr< const \fBBasisnamesOne\fP > basis_one, int q)"
.br
.ti -1c
.RI "void \fBprecalculateMagneticMomentum\fP (std::shared_ptr< const \fBBasisnamesOne\fP > basis_one, int q)"
.br
.ti -1c
.RI "void \fBprecalculateDiamagnetism\fP (std::shared_ptr< const \fBBasisnamesOne\fP > basis_one, int k, int q)"
.br
.ti -1c
.RI "void \fBprecalculateMultipole\fP (std::shared_ptr< const \fBBasisnamesOne\fP > basis_one, int k)"
.br
.ti -1c
.RI "void \fBprecalculateRadial\fP (std::shared_ptr< const \fBBasisnamesOne\fP > basis_one, int k)"
.br
.ti -1c
.RI "real_t \fBgetElectricMomentum\fP (\fBStateOne\fP const &state_row, \fBStateOne\fP const &state_col)"
.br
.ti -1c
.RI "real_t \fBgetMagneticMomentum\fP (\fBStateOne\fP const &state_row, \fBStateOne\fP const &state_col)"
.br
.ti -1c
.RI "real_t \fBgetDiamagnetism\fP (\fBStateOne\fP const &state_row, \fBStateOne\fP const &state_col, int kappa)"
.br
.ti -1c
.RI "real_t \fBgetMultipole\fP (\fBStateOne\fP const &state_row, \fBStateOne\fP const &state_col, int kappa)"
.br
.ti -1c
.RI "real_t \fBgetRadial\fP (\fBStateOne\fP const &state_row, \fBStateOne\fP const &state_col, int kappa)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for pairinteraction from the source code\&.
