.TH "md__home_vikbond__documents_pi-hiwi_pi_pairinteraction_calc_wigner_symbols__t_o_d_o" 3 "Thu Feb 16 2017" "pairinteraction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home_vikbond__documents_pi-hiwi_pi_pairinteraction_calc_wigner_symbols__t_o_d_o \- TODO 

.IP "\(bu" 2
Compare results against http://fy.chalmers.se/subatom/wigxjpf/ 
.PP

