.TH "Serializer" 3 "Thu Feb 16 2017" "pairinteraction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Serializer \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBload\fP (const bytes_t &bytes)"
.br
.ti -1c
.RI "void \fBsave\fP (bytes_t &bytes)"
.br
.ti -1c
.RI "size_t \fBposition\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<class T > void \fBoperator<<\fP (\fBSerializer\fP &s, const T &data)"
.br
.ti -1c
.RI "template<class T > void \fBoperator<<\fP (\fBSerializer\fP &s, const std::vector< T > &data)"
.br
.ti -1c
.RI "template<class T > void \fBoperator>>\fP (\fBSerializer\fP &s, T &data)"
.br
.ti -1c
.RI "template<class T > void \fBoperator>>\fP (\fBSerializer\fP &s, std::vector< T > &data)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for pairinteraction from the source code\&.
