.TH "Serializable" 3 "Thu Feb 16 2017" "pairinteraction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Serializable \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBHamiltonianmatrix\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bytes_t & \fBserialize\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBdeserialize\fP (bytes_t &bytes)=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for pairinteraction from the source code\&.
