.TH "sqlite::handle" 3 "Thu Feb 16 2017" "pairinteraction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sqlite::handle \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhandle\fP (const std::string filename)"
.br
.ti -1c
.RI "\fBhandle\fP (const std::string filename, int flags)"
.br
.ti -1c
.RI "\fBresult\fP \fBquery\fP (const std::string sql)"
.br
.ti -1c
.RI "\fBresult\fP \fBquery\fP (std::stringstream const &ss)"
.br
.ti -1c
.RI "void \fBexec\fP (const std::string sql)"
.br
.ti -1c
.RI "void \fBexec\fP (std::stringstream const &ss)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for pairinteraction from the source code\&.
