.TH "StateOne" 3 "Thu Feb 16 2017" "pairinteraction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StateOne \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBState\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStateOne\fP (idx_t idx, int n, int l, float s, float j, float m)"
.br
.ti -1c
.RI "\fBStateOne\fP (idx_t idx, int n, int l, float j, float m)"
.br
.ti -1c
.RI "\fBStateOne\fP (int n, int l, float j, float m)"
.br
.ti -1c
.RI "\fBStateOne\fP (int n, int l, float s, float j, float m)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "int \fBl\fP"
.br
.ti -1c
.RI "float \fBs\fP"
.br
.ti -1c
.RI "float \fBj\fP"
.br
.ti -1c
.RI "float \fBm\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &out, const \fBStateOne\fP &state)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBStateOne\fP &s1, const \fBStateOne\fP &s2)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBStateOne\fP &s1, const \fBStateOne\fP &s2)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBStateOne\fP &s1, const \fBStateOne\fP &s2)"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBStateOne\fP &s1, const \fBStateOne\fP &s2)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for pairinteraction from the source code\&.
