.TH "State" 3 "Thu Feb 16 2017" "pairinteraction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
State \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBStateOne\fP, and \fBStateTwo\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBState\fP (idx_t idx)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "idx_t \fBidx\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for pairinteraction from the source code\&.
