.TH "Symmetry" 3 "Thu Feb 16 2017" "pairinteraction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Symmetry \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "parity_t \fBinversion\fP"
.br
.ti -1c
.RI "parity_t \fBreflection\fP"
.br
.ti -1c
.RI "parity_t \fBpermutation\fP"
.br
.ti -1c
.RI "int \fBrotation\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBSymmetry\fP &s1, const \fBSymmetry\fP &s2)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for pairinteraction from the source code\&.
