.TH "Triple" 3 "Thu Feb 16 2017" "pairinteraction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Triple \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTriple\fP (idx_t row, idx_t col, scalar_t val)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "idx_t \fBrow\fP"
.br
.ti -1c
.RI "idx_t \fBcol\fP"
.br
.ti -1c
.RI "scalar_t \fBval\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for pairinteraction from the source code\&.
