.TH "Whittaker" 3 "Thu Feb 16 2017" "pairinteraction" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Whittaker \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWhittaker\fP (\fBQuantumDefect\fP const &qd)"
.br
.RI "\fIConstructor\&. \fP"
.ti -1c
.RI "std::vector< real_t > \fBaxis\fP () const "
.br
.RI "\fIx values \fP"
.ti -1c
.RI "std::vector< real_t > \fBintegrate\fP ()"
.br
.RI "\fIEvaluate the radial wavefunction\&. \fP"
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static constexpr real_t \fBpower_kernel\fP (int power)"
.br
.RI "\fIPower kernel for matrix elements\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "real_t const \fBdx\fP"
.br
.RI "\fIIntegration step size\&. \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Whittaker::Whittaker (\fBQuantumDefect\fP const & qd)"

.PP
Constructor\&. The constructor initializes the \fCqd\fP member and sets the initial condition for the integrator\&. It determines the outer integration bound by semiclassical and empirical arguments\&. The inner intergration boundary is set to 1\&.
.PP
\fBParameters:\fP
.RS 4
\fIqd\fP Quantum defect data (parameters for the potentials) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "std::vector< real_t > Whittaker::axis () const"

.PP
x values Returns the domain on which the wavefunction was evaluated\&.
.PP
\fBReturns:\fP
.RS 4
vector with radial points 
.RE
.PP

.SS "std::vector< real_t > Whittaker::integrate ()"

.PP
Evaluate the radial wavefunction\&. This does not perform an integration but merely evaluates the \fBWhittaker\fP functions over the domain\&.
.PP
\fBReturns:\fP
.RS 4
vector with wavefunction amplitude 
.RE
.PP

.SS "static constexpr real_t Whittaker::power_kernel (int power)\fC [inline]\fP, \fC [static]\fP"

.PP
Power kernel for matrix elements\&. The power kernel accounts for the fact that for the \fBWhittaker\fP functions the domain is linear scaled\&. This is important for the calculation of matrix elements\&.
.PP
\fBParameters:\fP
.RS 4
\fIpower\fP exponent of r 
.RE
.PP
\fBReturns:\fP
.RS 4
power kernel 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for pairinteraction from the source code\&.
